// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyG9u7EknnH6BTSsBMYbSXHYjzRmLhwtY',
    appId: '1:516152774492:web:5c64da4fc801a9593ebb99',
    messagingSenderId: '516152774492',
    projectId: 'amsyss',
    authDomain: 'amsyss.firebaseapp.com',
    storageBucket: 'amsyss.appspot.com',
    measurementId: 'G-BQYBETJ7NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNngzC6KqyuP6QDyd7DdTAYm4v_dvaBzY',
    appId: '1:516152774492:android:4bec450075b52bfe3ebb99',
    messagingSenderId: '516152774492',
    projectId: 'amsyss',
    storageBucket: 'amsyss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmhneMpRAesaAIAs1IZyt6847-lezPOz4',
    appId: '1:516152774492:ios:e501362afeb1dcbb3ebb99',
    messagingSenderId: '516152774492',
    projectId: 'amsyss',
    storageBucket: 'amsyss.appspot.com',
    iosBundleId: 'com.example.amsystm',
  );
}
